resources:
  - config.yaml
  - mailcore.yaml
  - mailcoreservice.yaml
  - maildatabase.yaml
  - mtaservice.yaml
  - namespace.yaml
  - nginx-config.yaml
  - secrets.yaml
  - storage.yaml
  - suiteservice.yaml
  - webservice.yaml
commonAnnotations:
  owner: chenzeng
  email: "chenzeng765@163.com"
namespace: mail
